name: dio_form_json
description: Support upload files with JSON data for Dio
version: 1.0.0
homepage: https://github.com/joutvhu/form_json
repository: https://github.com/joutvhu/form_json/tree/main/dio

environment:
  sdk: '>=2.15.0'

dependencies:
  dio: ">=4.0.1 <6.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
