name: Publish Dart Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      continue: ${{ steps.should_continue.outputs.continue }}
    steps:
      - name: Get Current Release
        id: current_release
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Should continue
        id: should_continue
        run: |
          echo "::set-output name=continue::${{ github.event_name == 'workflow_dispatch' || contains(steps.current_release.outputs.tag_name, '_dio') || !contains(steps.current_release.outputs.tag_name, '_') }}"

  publish:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.continue == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Current Release
        id: current_release
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Setup Credentials
        uses: joutvhu/write-file@v1
        with:
          path: ~/.config/dart/pub-credentials.json
          contents: ${{ secrets.PUB_CREDENTIALS }}
          write_mode: overwrite

      - name: Install dependencies
        run: dart pub get
        working-directory: dio

      - name: Publish package
        run: dart pub publish -f
        working-directory: dio
