name: Publish NuGet Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      validate:
        type: choice
        description: Should validate nupkg?
        options:
          - true
          - false

jobs:
  publish:
    runs-on: windows-latest
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.ref, '_aspnet') || !contains(github.ref, '_') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Create NuGet package
        run: dotnet pack --configuration Release --output ./nuget
        working-directory: aspnet

      - name: Install NuGet validator
        if: ${{ github.event_name == 'release' || github.event.inputs.validate == true }}
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global

      - name: Validate package
        if: ${{ github.event_name == 'release' || github.event.inputs.validate == true }}
        run: meziantou.validate-nuget-package (Get-ChildItem "./nuget/*.nupkg") --excluded-rule-ids 32,74,111
        working-directory: aspnet

      - name: Run tests
        run: dotnet test --configuration Release
        working-directory: aspnet

      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NuGet Registry
        run: |
          foreach($file in (Get-ChildItem "./nuget" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
        working-directory: aspnet

      - name: Publish to GitHub Registry
        if: ${{ github.event_name == 'release' && steps.get_current_release.outputs.prerelease == 'false' && steps.get_current_release.outputs.draft == 'false' }}
        run: |
          dotnet nuget add source --username joutvhu --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/joutvhu/index.json"
          foreach($file in (Get-ChildItem "./nuget" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github" --skip-duplicate
          }
        working-directory: aspnet
