name: Publish Maven Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Write Secret Key Ring File
        uses: joutvhu/write-file@v1
        with:
          path: spring/secrets/secret-key.gpg
          contents: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          write_mode: overwrite
          encoding: base64

      - name: Write Gradle Properties File
        uses: joutvhu/write-file@v1
        with:
          path: spring/gradle.properties
          contents: ${{ secrets.GRADLE_SECRET_PROPERTIES }}
          write_mode: overwrite

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: spring

      - name: Build with Gradle
        run: ./gradlew clean builds
        working-directory: spring

    #   - name: Get Current Release
    #     id: get_current_release
    #     uses: joutvhu/get-release@v1
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     working-directory: ./spring

      - name: Publish to Sonatype Packages
        run: ./gradlew publishMavenPublicationToSonatypeRepository

    #   - name: Publish to GitHub Packages
    #     if: ${{ steps.get_current_release.outputs.prerelease == 'false' && steps.get_current_release.outputs.draft == 'false' }}
    #     run: ./gradlew publishMavenPublicationToGithubRepository
    #     working-directory: ./spring
