name: Publish Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.ref, '_spring') || !contains(github.ref, '_') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Write Secret Key Ring File
        uses: joutvhu/write-file@v1
        with:
          path: spring/secrets/secret-key.gpg
          contents: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          write_mode: overwrite
          encoding: base64

      - name: Write Gradle Properties File
        uses: joutvhu/write-file@v1
        with:
          path: spring/gradle.properties
          contents: ${{ secrets.GRADLE_SECRET_PROPERTIES }}
          write_mode: overwrite

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: spring

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: spring

      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Sonatype Packages
        run: ./gradlew publishMavenPublicationToSonatypeRepository
        working-directory: spring

      - name: Publish to GitHub Packages
        if: ${{ github.event_name == 'release' && steps.get_current_release.outputs.prerelease == 'false' && steps.get_current_release.outputs.draft == 'false' }}
        run: ./gradlew publishMavenPublicationToGithubRepository
        working-directory: spring
